Repository juju/docs, pull requests merged in 2018-02, with the labels that each got.

#2443 Backport #2442 to 2.3
  src/en/howto-updateseries.md
  src/navigation.tpl
Labels: doc-utils

#2447 generic credentials management and update azure credentials example
  src/en/credentials.md
  src/en/help-azure.md
Labels: 2.0, 2.2, 2.3

#2448 Backport #2447 to 2.3
  src/en/credentials.md
  src/en/help-azure.md
Labels: doc-utils

#2449 Backport #2447 to 2.2
  src/en/credentials.md
  src/en/help-azure.md
Labels: doc-utils

#2446 fix add manual dialog
  src/en/clouds-manual.md
  src/en/clouds.md
  src/en/credentials.md
Labels: 2.0, 2.2, 2.3

#2451 Backport #2446 to 2.3
  src/en/clouds-manual.md
  src/en/clouds.md
  src/en/credentials.md
Labels: doc-utils

#2452 Backport #2446 to 2.2
  src/en/clouds-manual.md
  src/en/clouds.md
  src/en/credentials.md
Labels: doc-utils

#2464 Fix list
  src/en/models-config.md
Labels: 2.0, 2.2, 2.3, please backport

#2465 Backport #2464 to 2.3
  src/en/models-config.md
Labels: doc-utils

#2467 Backport #2464 to 2.0
  src/en/models-config.md
Labels: doc-utils

#2466 Backport #2464 to 2.2
  src/en/models-config.md
Labels: doc-utils
