Repository juju/docs, pull requests merged in 2018-05, with the labels that each got.

#2656 Add new hook tool entry: goal-state
  src/en/reference-hook-tools.md
Labels: 2.4

#2673 Add JUJU_VERSION variable
  src/en/reference-environment-variables.md
Labels: 2.3

#2677 Backport #2673 to 2.3
  src/en/reference-environment-variables.md
Labels: doc-utils

#2675 Add controller keys for OpenStack GBP
  src/en/controllers-config.md
Labels: 2.3

#2678 Backport #2675 to 2.3
  src/en/controllers-config.md
Labels: doc-utils

#2670 Review constraints
  src/en/charms-bundles.md
  src/en/charms-constraints.md
  src/en/charms-deploying-advanced.md
  src/en/charms-deploying.md
  src/en/charms-scaling.md
  src/en/clouds-lxd-resources.md
  src/en/controllers-creating.md
  src/en/models.md
  src/en/network-spaces.md
  src/en/reference-constraints.md
Labels: 2.2, 2.3

#2676 Preference given to "agent binaries" instead of "tools"
  src/en/howto-privatecloud.md
  src/en/juju-block.md
  src/en/juju-centos.md
  src/en/models-upgrade-notes.md
Labels: 2.3

#2684 Backport #2676 to 2.3
  src/en/howto-privatecloud.md
  src/en/juju-block.md
  src/en/juju-centos.md
  src/en/models-upgrade-notes.md
Labels: doc-utils

#2689 Add 2.4-beta2 Release Notes
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: 2.4

#2697 Add 2.3.8 to release notes and install page - devel
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: devel

#2698 Backport #2697 to devel
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2672 Rewrite high availability, include 2.4 changes
  src/en/charms-ha.md
  src/en/controllers-ha.md
  src/en/metadata.yaml
  src/navigation.tpl
Labels: devel

#2701 Backport #2672 to devel
  src/en/charms-ha.md
  src/en/controllers-ha.md
  src/en/metadata.yaml
  src/navigation.tpl
Labels: doc-utils

#2674 Add ICMP protocol to hook tools
  src/en/reference-hook-tools.md
Labels: 2.3, devel

#2705 Backport #2674 to devel
  src/en/reference-hook-tools.md
Labels: doc-utils

#2706 Backport #2674 to 2.3
  src/en/reference-hook-tools.md
Labels: doc-utils

#2711 Fix for shabby jinja2
  src/en/developer-layer-example.md
Labels: 1.25, 2.2, 2.3, 2.4, devel, please backport

#2712 Backport #2711 to devel
  src/en/developer-layer-example.md
Labels: doc-utils

#2714 Backport #2711 to 2.2
  src/en/developer-layer-example.md
Labels: doc-utils

#2713 Backport #2711 to 2.3
  src/en/developer-layer-example.md
Labels: doc-utils

#2704 Add 2.4-beta3 release notes
  src/en/reference-release-notes.md
Labels: devel

#2700 Update relnotes and install page with 2.3.8 release
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: 2.2

#2716 Backport #2704 to devel
  src/en/reference-release-notes.md
Labels: doc-utils

#2720 Add some extra info to `resolved` command and clean up wording
  src/en/developer-debugging.md
  src/en/models-config.md
  src/en/troubleshooting-removals.md
Labels: devel

#2685 Review Azure
  src/en/charms-ha.md
  src/en/clouds-maas.md
  src/en/getting-started.md
  src/en/help-aws.md
  src/en/help-azure-advanced.md
  src/en/help-azure.md
  src/en/tut-users.md
Labels: 2.2, 2.3, devel

#2730 Backport #2685 to devel
  src/en/charms-ha.md
  src/en/clouds-maas.md
  src/en/getting-started.md
  src/en/help-aws.md
  src/en/help-azure-advanced.md
  src/en/help-azure.md
  src/en/tut-users.md
Labels: doc-utils

#2731 Backport #2685 to 2.3
  src/en/charms-ha.md
  src/en/clouds-maas.md
  src/en/getting-started.md
  src/en/help-aws.md
  src/en/help-azure-advanced.md
  src/en/help-azure.md
  src/en/tut-users.md
Labels: doc-utils

#2732 Backport #2685 to 2.2
  src/en/charms-ha.md
  src/en/clouds-maas.md
  src/en/getting-started.md
  src/en/help-aws.md
  src/en/help-azure-advanced.md
  src/en/help-azure.md
  src/en/tut-users.md
Labels: doc-utils
