Repository juju/docs, pull requests merged in 2018-07, with the labels that each got.

#2828 Rewrite cahrms.reactive debugging instructions
  src/en/developer-debugging.md
Labels: 2.2, 2.3, 2.4

#2806 Clarifying cloud pages
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/clouds-maas.md
  src/en/clouds-manual.md
  src/en/clouds.md
  src/en/controllers-config.md
Labels: 2.3, 2.4, devel

#2838 Backport #2837 to devel
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2836 fix link in charms-bundles.md
  src/en/charms-bundles.md
Labels: 2.3, 2.4, devel

#2843 Backport #2836 to devel
  src/en/charms-bundles.md
Labels: doc-utils

#2844 Backport #2836 to 2.4
  src/en/charms-bundles.md
Labels: doc-utils

#2845 Backport #2836 to 2.3
  src/en/charms-bundles.md
Labels: doc-utils

#2848 Add local charm guidance to charms-bundle.md
  src/en/charms-bundles.md
Labels: 2.2, 2.3, 2.4, devel

#2849 Backport #2848 to devel
  src/en/charms-bundles.md
Labels: doc-utils

#2850 Backport #2848 to 2.4
  src/en/charms-bundles.md
Labels: doc-utils

#2851 Backport #2848 to 2.3
  src/en/charms-bundles.md
Labels: doc-utils

#2853 Explain default series in metadata.yaml
  src/en/authors-charm-metadata.md
Labels: 2.2, 2.3, 2.4, devel

#2855 Backport #2853 to devel
  src/en/authors-charm-metadata.md
Labels: doc-utils

#2856 Backport #2853 to 2.4
  src/en/authors-charm-metadata.md
Labels: doc-utils

#2857 Backport #2853 to 2.3
  src/en/authors-charm-metadata.md
Labels: doc-utils

#2858 Backport #2853 to 2.2
  src/en/authors-charm-metadata.md
Labels: doc-utils

#2854 Add new requirement (controller to provider)
  src/en/charms-offline-config.md
Labels: 2.2, 2.3, 2.4, devel

#2859 Backport #2854 to devel
  src/en/charms-offline-config.md
Labels: doc-utils

#2860 Backport #2854 to 2.4
  src/en/charms-offline-config.md
Labels: doc-utils

#2861 Backport #2854 to 2.3
  src/en/charms-offline-config.md
Labels: doc-utils

#2862 Backport #2854 to 2.2
  src/en/charms-offline-config.md
Labels: doc-utils

#2866 Fix links and miscellaneous small items on Log pages
  src/en/troubleshooting-logs.md
  src/en/troubleshooting.md
Labels: 2.3, 2.4, devel

#2869 Backport #2866 to devel
  src/en/troubleshooting-logs.md
  src/en/troubleshooting.md
Labels: doc-utils

#2870 Backport #2866 to 2.4
  src/en/troubleshooting-logs.md
  src/en/troubleshooting.md
Labels: doc-utils

#2871 Backport #2866 to 2.3
  src/en/troubleshooting-logs.md
  src/en/troubleshooting.md
Labels: doc-utils

#2864 Move juju availability zone variable
  src/en/reference-environment-variables.md
Labels: 2.2, 2.3, 2.4, devel

#2872 Backport #2864 to devel
  src/en/reference-environment-variables.md
Labels: doc-utils

#2873 Backport #2864 to 2.4
  src/en/reference-environment-variables.md
Labels: doc-utils

#2874 Backport #2864 to 2.3
  src/en/reference-environment-variables.md
Labels: doc-utils

#2867 Fixup implicit relations
  src/en/authors-implicit-relations.md
  src/en/authors-relations.md
  src/en/authors-subordinate-applications.md
  src/en/metadata.yaml
Labels: 2.2, 2.3, 2.4, devel

#2876 Backport #2867 to devel
  src/en/authors-implicit-relations.md
  src/en/authors-relations.md
  src/en/authors-subordinate-applications.md
  src/en/metadata.yaml
Labels: doc-utils

#2877 Backport #2867 to 2.4
  src/en/authors-implicit-relations.md
  src/en/authors-relations.md
  src/en/authors-subordinate-applications.md
  src/en/metadata.yaml
Labels: doc-utils

#2878 Backport #2867 to 2.3
  src/en/authors-implicit-relations.md
  src/en/authors-relations.md
  src/en/authors-subordinate-applications.md
  src/en/metadata.yaml
Labels: doc-utils

#2832 Review clouds-manual.md
  src/en/clouds-maas.md
  src/en/clouds-manual.md
  src/en/clouds.md
Labels: 2.2, 2.3, 2.4, devel

#2887 Backport #2832 to devel
  src/en/clouds-maas.md
  src/en/clouds-manual.md
  src/en/clouds.md
Labels: doc-utils

#2889 Backport #2832 to 2.3
  src/en/clouds-maas.md
  src/en/clouds-manual.md
  src/en/clouds.md
Labels: doc-utils

#2893 A null 'arch' constraint is not valid
  src/en/reference-constraints.md
Labels: 2.2, 2.3, 2.4, devel

#2895 Backport #2893 to devel
  src/en/reference-constraints.md
Labels: doc-utils

#2896 Backport #2893 to 2.4
  src/en/reference-constraints.md
Labels: doc-utils

#2897 Backport #2893 to 2.3
  src/en/reference-constraints.md
Labels: doc-utils

#2894 Fix links in menu
  src/en/metadata.yaml
Labels: 2.2, 2.3, 2.4, devel

#2899 Backport #2894 to devel
  src/en/metadata.yaml
Labels: doc-utils

#2900 Backport #2894 to 2.4
  src/en/metadata.yaml
Labels: doc-utils

#2901 Backport #2894 to 2.3
  src/en/metadata.yaml
Labels: doc-utils

#2863 Improve UX clouds and credentials
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/clouds.md
  src/en/credentials.md
  src/en/help-aws.md
  src/en/help-google.md
  src/en/help-openstack.md
  src/en/users.md
Labels: 2.2, 2.3, 2.4, devel

#2907 [2.4.1] Add release notes and update install page
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: 2.2, 2.3, 2.4, devel

#2908 Backport #2907 to devel
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2909 Backport #2907 to 2.4
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2910 Backport #2907 to 2.3
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2911 Backport #2907 to 2.2
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2913 Backport #2912 to devel
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2914 Backport #2912 to 2.4
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2915 Backport #2912 to 2.3
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2917 Backport #2916 to devel
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2918 Backport #2916 to 2.4
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2919 Backport #2916 to 2.3
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2925 Backport #2924 to devel
  src/en/authors-charm-best-practice.md
  src/en/authors-charm-store.md
  src/en/charm-review-process.md
  src/en/contact-us.md
  src/en/reference-release-notes-1.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2926 Backport #2924 to 2.4
  src/en/authors-charm-best-practice.md
  src/en/authors-charm-store.md
  src/en/charm-review-process.md
  src/en/contact-us.md
  src/en/reference-release-notes-1.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2927 Backport #2924 to 2.3
  src/en/authors-charm-best-practice.md
  src/en/authors-charm-store.md
  src/en/charm-review-process.md
  src/en/contact-us.md
  src/en/reference-release-notes-1.md
  src/en/reference-release-notes.md
Labels: doc-utils

#2920 Minor rewording and additions to 2.4.1 release notes
  src/en/reference-release-notes.md
Labels: 2.3, 2.4, devel

#2928 Backport #2920 to devel
  src/en/reference-release-notes.md
Labels: doc-utils

#2929 Backport #2920 to 2.4
  src/en/reference-release-notes.md
Labels: doc-utils

#2930 Backport #2920 to 2.3
  src/en/reference-release-notes.md
Labels: doc-utils

#2922 Add LXD clustering
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
Labels: 2.4
