Repository juju/docs, pull requests merged in 2018-06, with the labels that each got.

#2737 Review of metadata page
  src/en/authors-charm-metadata.md
  src/en/charms-deploying-advanced.md
  src/en/reference-hook-tools.md
Labels: 2.2, 2.3, devel

#2740 Backport #2737 to devel
  src/en/authors-charm-metadata.md
  src/en/charms-deploying-advanced.md
  src/en/reference-hook-tools.md
Labels: doc-utils

#2741 Backport #2737 to 2.3
  src/en/authors-charm-metadata.md
  src/en/charms-deploying-advanced.md
  src/en/reference-hook-tools.md
Labels: doc-utils

#2739 Add Juju-centric proxy values
  src/en/charms-offline-config.md
  src/en/charms-offline-strategies.md
  src/en/models-config.md
Labels: devel

#2748 Backport #2739 to devel
  src/en/charms-offline-config.md
  src/en/charms-offline-strategies.md
  src/en/models-config.md
Labels: doc-utils

#2744 Update command output re removal of relations information
  src/en/charms-relations.md
  src/en/models-cmr-scene-1.md
  src/en/models-cmr-scene-2.md
Labels: 2.3, devel

#2749 Backport #2744 to devel
  src/en/charms-relations.md
  src/en/models-cmr-scene-1.md
  src/en/models-cmr-scene-2.md
Labels: doc-utils

#2750 Backport #2744 to 2.3
  src/en/charms-relations.md
  src/en/models-cmr-scene-1.md
  src/en/models-cmr-scene-2.md
Labels: doc-utils

#2745 Review troubleshooting-upgrade page
  src/en/developer-debugging.md
  src/en/troubleshooting-upgrade.md
Labels: 2.2, 2.3, devel

#2751 Backport #2745 to devel
  src/en/developer-debugging.md
  src/en/troubleshooting-upgrade.md
Labels: doc-utils

#2752 Backport #2745 to 2.3
  src/en/developer-debugging.md
  src/en/troubleshooting-upgrade.md
Labels: doc-utils

#2758 Review charms-relations.md
  src/en/charms-relations.md
  src/en/metadata.yaml
Labels: 2.2, 2.3, devel

#2760 Backport #2758 to devel
  src/en/charms-relations.md
  src/en/metadata.yaml
Labels: doc-utils

#2762 Backport #2755 to devel
  src/en/charms-destroy.md
  src/en/charms-scaling.md
  src/en/reference-numbering.md
Labels: doc-utils

#2763 Backport #2755 to 2.3
  src/en/charms-destroy.md
  src/en/charms-scaling.md
  src/en/reference-numbering.md
Labels: doc-utils

#2769 Provide better coverage of `add-machine` command
  src/en/charms-deploying.md
  src/en/charms-scaling.md
Labels: 2.3, devel

#2776 Backport #2769 to devel
  src/en/charms-deploying.md
  src/en/charms-scaling.md
Labels: doc-utils

#2777 Backport #2769 to 2.3
  src/en/charms-deploying.md
  src/en/charms-scaling.md
Labels: doc-utils

#2770 Clarify LXD install and improve link/title stuff
  src/en/charms-storage.md
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/clouds.md
  src/en/introducing-2.md
Labels: 2.2, 2.3, devel

#2779 Backport #2770 to devel
  src/en/charms-storage.md
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/clouds.md
  src/en/introducing-2.md
Labels: doc-utils

#2780 Backport #2770 to 2.3
  src/en/charms-storage.md
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/clouds.md
  src/en/introducing-2.md
Labels: doc-utils

#2782 Fixup howto privatecloud
  src/en/help-openstack.md
  src/en/howto-privatecloud.md
Labels: 2.2

#2774 Fix up HA restore
  src/en/controllers-backup.md
Labels: 2.3, devel

#2786 Backport #2774 to devel
  src/en/controllers-backup.md
Labels: doc-utils

#2787 Backport #2774 to 2.3
  src/en/controllers-backup.md
Labels: doc-utils

#2784 Add two OpenStack config keys
  src/en/controllers-config.md
Labels: 2.2, 2.3, devel

#2789 Backport #2784 to devel
  src/en/controllers-config.md
Labels: doc-utils

#2790 Backport #2784 to 2.3
  src/en/controllers-config.md
Labels: doc-utils

#2792 Update commands.md file for 2.4
  src/en/commands.md
Labels: devel

#2793 Backport #2792 to devel
  src/en/commands.md
Labels: doc-utils

#2767 Replace `update-series` command with `set-series`
  src/en/howto-updateseries.md
Labels: devel

#2794 Backport #2767 to devel
  src/en/howto-updateseries.md
Labels: doc-utils

#2800 Backport #2799 to devel
  src/en/clouds-lxd-resources.md
Labels: doc-utils

#2801 Backport #2773 to devel
  src/en/clouds-LXD.md
  src/en/clouds-maas-manual.md
  src/en/clouds-maas.md
  src/en/clouds-openstack-manual.md
  src/en/clouds.md
  src/en/help-aws.md
  src/en/help-azure.md
  src/en/help-google.md
  src/en/help-joyent.md
  src/en/help-openstack.md
  src/en/help-oracle.md
  src/en/help-rackspace.md
  src/en/help-vmware.md
  src/en/tut-users.md
Labels: doc-utils

#2785 Explain charm status of 'blocked' better
  src/en/reference-status.md
Labels: 2.2, 2.3, devel

#2803 Backport #2785 to devel
  src/en/reference-status.md
Labels: doc-utils

#2804 Backport #2785 to 2.3
  src/en/reference-status.md
Labels: doc-utils

#2805 Backport #2785 to 2.2
  src/en/reference-status.md
Labels: doc-utils

#2808 Add supporting text for 'juju-mgmt-space' and 'juju-ha-space' controller configuration options
  src/en/controllers-config.md
Labels: devel

#2810 Backport #2808 to devel
  src/en/controllers-config.md
Labels: doc-utils

#2795 Add --keep-latest option to `remove-backup`
  src/en/controllers-backup.md
Labels: devel

#2813 Backport #2795 to devel
  src/en/controllers-backup.md
Labels: doc-utils

#2788 Review charms bundles
  src/en/authors-charm-store.md
  src/en/charms-bundles-gui.md
  src/en/charms-bundles.md
  src/en/charms-config.md
  src/en/developer-getting-started.md
  src/en/getting-started.md
  src/en/jaas-cli.md
  src/en/juju-concepts.md
  src/en/juju-quickstart.md
  src/en/metadata.yaml
  src/en/network-spaces.md
  src/en/whats-new.md
Labels: 2.3, devel

#2814 Backport #2788 to devel
  src/en/authors-charm-store.md
  src/en/charms-bundles-gui.md
  src/en/charms-bundles.md
  src/en/charms-config.md
  src/en/developer-getting-started.md
  src/en/getting-started.md
  src/en/jaas-cli.md
  src/en/juju-concepts.md
  src/en/juju-quickstart.md
  src/en/metadata.yaml
  src/en/network-spaces.md
  src/en/whats-new.md
Labels: doc-utils

#2809 [2.4] Update Release Notes
  src/en/reference-release-notes.md
Labels: 2.2, 2.3, devel

#2816 Backport #2809 to devel
  src/en/reference-release-notes.md
Labels: doc-utils

#2811 Add What' s new 2.4
  src/en/whats-new.md
Labels: 2.4

#2812 Update install page for 2.4.0
  src/en/reference-install.md
Labels: 2.2, 2.3, devel

#2821 Backport #2812 to devel
  src/en/reference-install.md
Labels: doc-utils

#2822 Backport #2812 to 2.3
  src/en/reference-install.md
Labels: doc-utils

#2823 Backport #2812 to 2.2
  src/en/reference-install.md
Labels: doc-utils

#2825 Nav and link changes for What's new
  src/en/metadata.yaml
  src/en/whats-new.md
Labels: 2.4, devel

#2826 Backport #2825 to devel
  src/en/metadata.yaml
  src/en/whats-new.md
Labels: doc-utils

#2827 Backport #2825 to 2.4
  src/en/metadata.yaml
  src/en/whats-new.md
Labels: doc-utils
