Repository juju/docs, pull requests merged in 2018-04, with the labels that each got.

#2591 Update install page
  src/en/reference-install.md
Labels: 2.3, 2.4, devel, please backport

#2593 Backport #2591 to 2.3
  src/en/reference-install.md
Labels: doc-utils

#2525 Review and refactor charms-deploying.md
  src/en/charms-bundles.md
  src/en/charms-constraints.md
  src/en/charms-deploying-advanced.md
  src/en/charms-deploying.md
  src/en/charms-scaling.md
  src/en/charms-upgrading.md
  src/en/clouds-manual.md
  src/en/network-spaces.md
Labels: 2.2, 2.3, please backport

#2596 Backport #2525 to 2.3
  src/en/charms-bundles.md
  src/en/charms-constraints.md
  src/en/charms-deploying-advanced.md
  src/en/charms-deploying.md
  src/en/charms-scaling.md
  src/en/charms-upgrading.md
  src/en/clouds-manual.md
  src/en/network-spaces.md
Labels: doc-utils

#2470 update howto-updateseries per lp:1750907
  src/en/howto-updateseries.md
Labels: 2.3

#2602 Backport #2589 to 2.3
  src/en/clouds.md
  src/en/controllers-creating.md
  src/en/help-aws.md
Labels: doc-utils

#2604 override logging plus some minor fixes
  src/en/juju-concepts.md
  src/en/troubleshooting-logs.md
Labels: 2.2, 2.3

#2618 Backport #2604 to 2.3
  src/en/juju-concepts.md
  src/en/troubleshooting-logs.md
Labels: doc-utils

#2605 fix PR 2530
  src/en/charms-storage.md
Labels: 2.3

#2614 Add container model config options
  src/en/charms-offline-config.md
  src/en/models-config.md
Labels: 2.3

#2628 Backport #2614 to 2.3
  src/en/charms-offline-config.md
  src/en/models-config.md
Labels: doc-utils

#2607 Mention the `--force` and `--no-destroy` options for removing storage
  src/en/charms-storage.md
Labels: 2.3

#2629 Backport #2607 to 2.3
  src/en/charms-storage.md
Labels: doc-utils

#2606 Add '--force' option to one command and allow short offer name in other commands
  src/en/models-cmr-scene-2.md
  src/en/models-cmr.md
Labels: 2.3

#2630 Backport #2606 to 2.3
  src/en/models-cmr-scene-2.md
  src/en/models-cmr.md
Labels: doc-utils

#2615 Default release for controller hardcoded plus show how Bionic can be requested
  src/en/controllers-creating.md
Labels: 2.3

#2631 Backport #2615 to 2.3
  src/en/controllers-creating.md
Labels: doc-utils

#2632 Add 2.3.6 release notes
  src/en/reference-release-notes.md
Labels: 2.2, 2.3

#2634 Add 2.3.6 to install page
  src/en/reference-install.md
Labels: 2.2, 2.3

#2638 Backport #2632 to 2.3
  src/en/reference-release-notes.md
Labels: doc-utils

#2639 Backport #2632 to 2.2
  src/en/reference-release-notes.md
Labels: doc-utils

#2640 Backport #2634 to 2.3
  src/en/reference-install.md
Labels: doc-utils

#2646 Replace `upgrade-juju` with `upgrade-model`
  src/en/juju-block.md
  src/en/models-upgrade.md
  src/en/troubleshooting-upgrade.md
  src/en/users.md
Labels: 2.4

#2647 Show how to see credentials in use; document show-model
  src/en/credentials.md
  src/en/models.md
Labels: 2.4

#2649 Add show-credentials command and refactor a bit
  src/en/credentials.md
Labels: 2.4

#2654 Corrections and many improvements to hml's howto
  src/en/howto-updateseries.md
Labels: 2.3

#2655 Backport #2654 to 2.3
  src/en/howto-updateseries.md
Labels: doc-utils

#2598 Move over troubleshooting tips from PR 2525
  src/en/charms-deploying.md
  src/en/troubleshooting-additions.md
  src/en/troubleshooting.md
Labels: 2.2, 2.3

#2657 Backport #2598 to 2.3
  src/en/charms-deploying.md
  src/en/troubleshooting-additions.md
  src/en/troubleshooting.md
Labels: doc-utils

#2658 Backport #2598 to 2.2
  src/en/charms-deploying.md
  src/en/troubleshooting-additions.md
  src/en/troubleshooting.md
Labels: doc-utils

#2661 New release: 2.3.7 - Add release notes and update install page
  src/en/reference-install.md
  src/en/reference-release-notes.md
Labels: 2.2, 2.3

#2651 2.3 controller will always use Xenial
  src/en/controllers-creating.md
Labels: 2.3

#2667 Add two new controller configuration options
  src/en/controllers-config.md
Labels: 2.4

#2666 Fix controller table
  src/en/controllers-config.md
Labels: 2.3

#2668 Backport #2666 to 2.3
  src/en/controllers-config.md
Labels: doc-utils
