Repository juju/docs, pull requests merged in 2018-03, with the labels that each got.

#2473 Update release notes
  src/en/reference-release-notes.md
Labels: 2.0, 2.2, 2.3

#2474 Backport #2473 to 2.3
  src/en/reference-release-notes.md
Labels: doc-utils

#2475 Backport #2473 to 2.2
  src/en/reference-release-notes.md
Labels: doc-utils

#2476 Backport #2473 to 2.0
  src/en/reference-release-notes.md
Labels: doc-utils

#2453 spaces subnets bindings constraints
  src/en/network-spaces.md
Labels: 2.0, 2.2, 2.3

#2480 Backport #2453 to 2.3
  src/en/network-spaces.md
Labels: doc-utils

#2484 Backport #2483 to 2.3
  src/en/controllers-config.md
  src/en/troubleshooting-logs-remote.md
  src/en/troubleshooting-logs.md
  src/en/troubleshooting.md
Labels: doc-utils

#2487 audit logging: fix link and perform minor cleanup
  src/en/controllers-config.md
  src/en/troubleshooting-logs.md
Labels: 2.3

#2488 Backport #2487 to 2.3
  src/en/controllers-config.md
  src/en/troubleshooting-logs.md
Labels: doc-utils

#2478 update MAAS links
  src/en/charms-ha.md
  src/en/clouds-maas.md
Labels: 2.0, 2.2, 2.3

#2491 Backport #2478 to 2.3
  src/en/charms-ha.md
  src/en/clouds-maas.md
Labels: doc-utils

#2492 Backport #2478 to 2.2
  src/en/charms-ha.md
  src/en/clouds-maas.md
Labels: doc-utils

#2496 Backport #2471 to 2.3
  htmldocs/media/tut-lxd-wiki-simple-browser-2.png
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/reference-install.md
  src/en/tut-lxd.md
Labels: doc-utils

#2497 Backport #2471 to 2.2
  htmldocs/media/tut-lxd-wiki-simple-browser-2.png
  src/en/clouds-LXD.md
  src/en/clouds-lxd-resources.md
  src/en/reference-install.md
  src/en/tut-lxd.md
Labels: doc-utils

#2495 Define and clean up application endpoint, interface, spaces, binding story
  src/en/charms-constraints.md
  src/en/charms-deploying.md
  src/en/juju-concepts.md
  src/en/network-spaces.md
Labels: 2.0, 2.2, 2.3

#2498 Backport #2495 to 2.3
  src/en/charms-constraints.md
  src/en/charms-deploying.md
  src/en/juju-concepts.md
  src/en/network-spaces.md
Labels: doc-utils

#2499 Backport #2495 to 2.2
  src/en/charms-constraints.md
  src/en/charms-deploying.md
  src/en/juju-concepts.md
  src/en/network-spaces.md
Labels: doc-utils

#2514 More on spaces
  htmldocs/media/juju-relations.png
  htmldocs/media/juju-relations.svg
  src/en/authors-charm-metadata.md
  src/en/authors-relations.md
  src/en/charms-bundles.md
  src/en/charms-constraints.md
  src/en/charms-deploying.md
  src/en/juju-concepts.md
  src/en/network-spaces.md
Labels: 2.2, 2.3, please backport

#2517 Backport #2514 to 2.3
  htmldocs/media/juju-relations.png
  htmldocs/media/juju-relations.svg
  src/en/authors-charm-metadata.md
  src/en/authors-relations.md
  src/en/charms-bundles.md
  src/en/charms-constraints.md
  src/en/charms-deploying.md
  src/en/juju-concepts.md
  src/en/network-spaces.md
Labels: doc-utils

#2519 charms-destroy and troubleshooting pages
  src/en/charms-destroy.md
  src/en/charms-relations.md
  src/en/troubleshooting-removals.md
  src/en/troubleshooting-upgrade.md
  src/en/troubleshooting.md
Labels: 2.2, 2.3, please backport

#2521 Backport #2519 to 2.3
  src/en/charms-destroy.md
  src/en/charms-relations.md
  src/en/troubleshooting-removals.md
  src/en/troubleshooting-upgrade.md
  src/en/troubleshooting.md
Labels: doc-utils

#2516 fix up and lighten headers
  src/en/tools-charm-tools.md
Labels: 2.2, 2.3, please backport

#2523 Backport #2516 to 2.3
  src/en/tools-charm-tools.md
Labels: doc-utils

#2524 Backport #2516 to 2.2
  src/en/tools-charm-tools.md
Labels: doc-utils

#2538 update charm helpers documentation url
  src/en/developer-getting-started.md
  src/en/developer-layers.md
  src/en/tools-charm-helpers.md
Labels: 2.2, 2.3, please backport

#2539 Backport #2538 to 2.3
  src/en/developer-getting-started.md
  src/en/developer-layers.md
  src/en/tools-charm-helpers.md
Labels: doc-utils

#2540 Backport #2538 to 2.2
  src/en/developer-getting-started.md
  src/en/developer-layers.md
  src/en/tools-charm-helpers.md
Labels: doc-utils

#2562 update release notes for 2.3.5
  src/en/reference-release-notes.md
Labels: 2.2, 2.3, please backport

#2564 Backport #2562 to 2.3
  src/en/reference-release-notes.md
Labels: doc-utils

#2565 Backport #2562 to 2.2
  src/en/reference-release-notes.md
Labels: doc-utils

#2574 Backport #2566 to 2.3
  src/en/models-upgrade.md
  src/en/users.md
Labels: doc-utils

#2575 Backport #2566 to 2.2
  src/en/models-upgrade.md
  src/en/users.md
Labels: doc-utils

#2576 Backport #2568 to 2.3
  src/en/models-config.md
Labels: doc-utils

#2577 Backport #2568 to 2.2
  src/en/models-config.md
Labels: doc-utils

#2578 Backport #2570 to 2.3
  src/en/users-auth.md
Labels: doc-utils

#2563 update commands file and implement some temporary fixes
  src/en/commands.md
Labels: 2.3, please backport

#2579 Backport #2563 to 2.3
  src/en/commands.md
Labels: doc-utils

#2580 Backport #2572 to 2.3
  src/en/models-config.md
Labels: doc-utils

#2581 Backport #2569 to 2.3
  src/en/controllers-config.md
  src/en/models-config.md
Labels: doc-utils

#2583 Backport #2567 to 2.3
  src/en/models-config.md
Labels: doc-utils

#2585 Backport #2571 to 2.3
  src/en/models.md
Labels: doc-utils

#2586 Backport #2573 to 2.3
  src/en/controllers-creating.md
  src/en/juju-concepts.md
  src/en/models-config.md
Labels: doc-utils

#2587 Backport #2573 to 2.2
  src/en/controllers-creating.md
  src/en/juju-concepts.md
  src/en/models-config.md
Labels: doc-utils
